# Should players be prevented from moving while frozen?
prevent-movement: true

# Should players be prevented from teleporting while frozen?
prevent-teleport: true

# Should players be prevented from executing commands while frozen?
prevent-commands: true

# This is a list of commands that will be prevented
# This list uses the String.startsWith method
# This means that blocking '/tp' will also block '/tpa' and '/tpo'
blocked-command-list:
  - "/tp"
  - "/spawn"
  - "/home"

# This is a list of commands that will be allowed
# Only add commands here if they are accidentally blocked
# Example: block `/tpa` but allow `/tpahere`
# This list also uses String.startsWith
allowed-command-list:
  - "/tpahere"

#remember freeze-all across restarts
freeze-all: false